name: Upload Docker image to ECR and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{env.ENVIRONMENT}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to AWS ECRs
      run: |
        aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 730335588229.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build Docker image
      run: |
        export COMMIT_HASH=$(git rev-parse --short HEAD)
        echo $COMMIT_HASH
        sudo docker build -t my-app:${{env.ENVIRONMENT}}-${COMMIT_HASH} .

    - name: Tag Docker image
      run: |
        export COMMIT_HASH=$(git rev-parse --short HEAD)
        sudo docker tag my-app:${{env.ENVIRONMENT}}-${COMMIT_HASH} 730335588229.dkr.ecr.us-east-1.amazonaws.com/my-app:${{env.ENVIRONMENT}}-${COMMIT_HASH}

    - name: Push Docker image to ECR
      run: |
        export COMMIT_HASH=$(git rev-parse --short HEAD)
        echo "Commit Hash: $COMMIT_HASH"
        sudo docker push 730335588229.dkr.ecr.us-east-1.amazonaws.com/my-app:${{env.ENVIRONMENT}}-${COMMIT_HASH}

    - name: Deploy Docker image to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2 instance public IP or DNS name
        username: ${{ secrets.EC2_USERNAME }}  # SSH username for EC2 instance
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key for accessing EC2 instance
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 730335588229.dkr.ecr.us-east-1.amazonaws.com
          # sudo docker pull 730335588229.dkr.ecr.us-east-1.amazonaws.com/my-app:${COMMIT_HASH}
          # sudo docker run -d -p 80:8080 730335588229.dkr.ecr.us-east-1.amazonaws.com/my-app:${COMMIT_HASH}
