name: Deploy Docker image to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335588229.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and push Docker image to ECR
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        docker buildx build -t 730335588229.dkr.ecr.us-east-1.amazonaws.com/my-app:${COMMIT_HASH} .
        docker push 730335588229.dkr.ecr.us-east-1.amazonaws.com/my-app:${COMMIT_HASH}

    - name: Deploy Docker image to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2 instance public IP or DNS name
        username: ${{ secrets.EC2_USERNAME }}  # SSH username for EC2 instance
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key for accessing EC2 instance
        port: ${{ secrets.SSH_PORT }}
        script: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 730335588229.dkr.ecr.us-east-1.amazonaws.com
          docker pull 730335588229.dkr.ecr.us-east-1.amazonaws.com/my-app:${COMMIT_HASH}
          docker run -d -p 80:8080 730335588229.dkr.ecr.us-east-1.amazonaws.com/my-app:${COMMIT_HASH}
