  name: Upload Docker image to ECR and Deploy to EC2

  on:
    push:
      branches:
        - main

  jobs:
    build-and-push:
      runs-on: ubuntu-latest
      env:
        ENVIRONMENT: ${{secrets.ENVIRONMENT }}
        
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to AWS ECRs
        run: |
          aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 730335588229.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker images
        run: |
          # export COMMIT_HASH=$(git rev-parse --short HEAD)
          # echo $COMMIT_HASH
          # echo "Hellooo>>>>"${GITHUB_SHA}
          # echo "SHORT_SHA>>>>>>=`echo ${GITHUB_SHA} | cut -c1-8`" >> "$COMMIT_HASH"
          # COMMIT_HASH=$(${GITHUB_SHA} | cut -c1-8)
          COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)
          echo "Hellooo>>>>${COMMIT_HASH}"
          sudo docker build -t my-app:${{env.ENVIRONMENT}}-${{ github.run_number }}-${COMMIT_HASH} .

      - name: Tag Docker image
        run: |
          COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)
          sudo docker tag my-app:${{env.ENVIRONMENT}}-${{ github.run_number }}-${COMMIT_HASH} 730335588229.dkr.ecr.us-east-1.amazonaws.com/my-app:${{env.ENVIRONMENT}}-${{ github.run_number }}-${COMMIT_HASH}

      - name: Push Docker image to ECR
        run: |
          COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)
          echo "Commit Hash: $COMMIT_HASH"
          sudo docker push 730335588229.dkr.ecr.us-east-1.amazonaws.com/my-app:${{env.ENVIRONMENT}}-${{ github.run_number }}-${COMMIT_HASH}

      - name: Deploy Docker image to EC2 instance
        run: |
          ssh -i <SSH_PRIVATE_KEY> -p <SSH_PORT> <EC2_USERNAME>@<EC2_HOST>
          ssh -i ~/.ssh/my_private_key.pem -p 22 ec2-user@ec2-11-22-33-44.compute-1.amazonaws.com
